include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - build
  - test

default:
  image: eclipse-temurin:21

  cache:
    key: gradle-${CI_COMMIT_REF_SLUG}
    unprotect: true

    paths:
      - .gradle

build:
  stage: build

  script:
    - ./gradlew build
    - mv build/libs/*/*.jar ./

  artifacts:
    name: DistantHorizonsSupport-${CI_COMMIT_REF_SLUG}-${CI_JOB_STARTED_AT}

    paths:
      - "./*.jar"
