# Where should the plugin store its database file?
# Required.
# Default: "{datadir}/data.sqlite"
database_path: "{datadir}/data.sqlite"

# Maximum supported render distance. Clients will be capped to this value.
# Required.
# Default: 1024
render_distance: 1024

# Are LOD features enabled at all?
# Disable if you only want to use the plugin for level key info in a proxied setup.
# Required.
# Default: true
distant_generation_enabled: true

# Number of parallel LOD requests per client.
# Required.
# Default: 20
full_data_request_concurrency_limit: 20

# Send LOD updates to players in real-time?
# Required.
# Default: true
real_time_updates_enabled: true

# How close to an update players have to be in order to receive it.
# Required.
# Default: 128
real_time_update_radius: 128

# Let clients ask for updates to LODs they've previously downloaded.
# Required.
# Default: true
login_data_sync_enabled: true

# How far away can a player request updates for during login sync?
# Required.
# Default: 128
login_data_sync_radius: 128

# How many login sync requests can a client send at once?
# Required.
# Default: 50
login_data_sync_rc_limit: 50

# Currently unsupported.
# Required.
# Default: 0
max_data_transfer_speed: 0

# Should new chunks be generated to build LODs?
# If you disable this, the plugin will not be able to create LODs in areas where chunks don't already exist.
# Optional.
# Default: true
#generate_new_chunks: false

# Show warning during startup if chunk generation is enabled?
# Optional.
# Default: true
#generate_new_chunks_warning: false

# How frequently (in seconds) should LODs be updated if world changes are detected?
# Required.
# Default: 5
lod_refresh_interval: 5

# Select which LOD builder to use.
# Valid options are: FullBuilder, FastOverworldBuilder, and None.
# Required.
# Default: FullBuilder
builder_type: FullBuilder

# Number of blocks to advance between each sample on the Y axis when generating LODs.
# A setting of 1 will sample every block, while 2 will sample every other block, and so on.
# CURRENTLY BROKEN. THIS VALUE IS IGNORED.
# Required.
# Default: 2
builder_resolution: 2

# Whether to include non-colliding blocks when they are the top-most block.
# True means tall grass, flowers, and snow will color the block below them.
# Optional.
# Default: true
#include_non-colliding_top_layer: false

# When running DHS on a proxied server, set this to a value that is unique to this specific server.
# Optional.
#level_key_prefix:

# Use the vanilla world border of the respective world.
# Optional.
# Default: true
#use_vanilla_world_border: false

# How many chunks beyond the vanilla world border can we see (if it's enabled)?. If set to auto, it uses the server's
# view distance, which effectively means that if standing at the border you can see as far as the server would generate
# chunks naturally.
# Optional.
# Default: auto
#vanilla_world_border_expansion: 12

# World specific settings.
# You can override any of the above settings on a per-world basis.
worlds:
  world:
    # Use builder that is optimized for overworld.
    builder_type: FastOverworldBuilder

    # When using the FastOverworldBuilder, should LODs always contain data down to at least sea level?
    # Enable if your world has floating islands or mountains/structures with large overhangs above sea level.
    # Optional.
    # Default: false
    #scan_to_sea_level: true

    # When using the FastOverworldBuilder, should the bottom data point be stretched to the lowest permitted build
    # height? This will make the LODs look more complete, and gives a theoretical boost to render performance.
    # Optional.
    # Default: true
    #fast_underfill: false

    # Limit LOD generation to within this area.
    # Optional.
    #border_center_x: 0
    #border_center_z: 0
    #border_radius: 5000

  world_nether:
    # It might make sense to have a lower view distance in the nether, since visibility will be low simply because of
    # the level design anyway.
    render_distance: 64

    # This is a hack to prevent light from shining through ceilings, mostly noticeable on the nether ceiling.
    # Only works with the FullBuilder, should only be used with builder_resolution=1, and does have some side effects.
    #perform_underglow_hack: true
    #builder_resolution: 1

# Number of worker threads used to generate LODs.
# Does not affect Folia servers.
# Required.
# Default: 4
scheduler_threads: 4

# Should we notify server admins when a new version of the plugin is available?
# Optional.
# Default: true
#check_for_updates: false

# Don't touch :)
config_version: 8
